name: test
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  clipboard: ^0.1.3
  fluttertoast: ^8.0.7
  url_launcher: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_name: "^0.0.1"
  flutter_lints: ^2.0.0

flutter_launcher_name:
  name: "Test App Flutter"



flutter:

  uses-material-design: true


  

